chore(fix): add new peer-deps tailwindcss and related
Still not working because of:

Error: PostCSS plugin postcss-import requires PostCSS 8. Update PostCSS or downgrade this plugin.